Documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/*', '.readthedocs.yml', 'README.md', 'LICENSE', 'MANIFEST.in']

Internal:
  - changed-files:
      - any-glob-to-any-file: ['.*', 'codecov.yml', 'setup.cfg', 'setup.py', 'versioneer.py', '.github/*', '.circleci/*', 'physiopy-repository-template/_version.py', 'requirements.txt', 'pyproject.toml']

Testing:
  - changed-files:
      - any-glob-to-any-file: ['physiopy-repository-template/tests/*', '.circleci/*']
