[tool.coverage.report]
exclude_lines = [
  'if __name__ == .__main__.:',
  'if TYPE_CHECKING:',
  'pragma: no cover',
]
precision = 2

[tool.coverage.run]
branch = true
cover_pylib = false
omit = [
  '**/__init__.py',
  '**/conftest.py',
  '**/**/_version.py',
  '**/**/cli/**',
  '**/**/due.py',
  '**/tests/**',
]

[tool.ruff]
extend-exclude = ['docs', 'versioneer.py', 'setup.py', '_version.py']
line-length = 88
target-version = 'py310'

[tool.ruff.format]
docstring-code-format = true
line-ending = 'lf'
quote-style = "single"

[tool.ruff.lint]
ignore = ['E402', 'F401', 'F811', 'E203', 'E501']
select = ['A', 'B', 'E', 'D', 'F', 'I', 'UP', 'W']

[tool.ruff.lint.pydocstyle]
convention = 'numpy'

[tool.ruff.lint.per-file-ignores]
'*' = [
  'B904', # 'Within an except clause, raise exceptions with raise ... from ...'
  'UP007', # 'Use `X | Y` for type annotations', requires python 3.10
]
'*.pyi' = ['E501']
'__init__.py' = ['F401']
'_version.py' = ['UP031']
'conftest.py' = ['D']
'due.py' = ['D']
'*/tests/*' = ['D']
'*/__init__.py' = ['F401', 'D']
'*/*/__init__.py' = ['F401', 'D']
'*/_version.py' = ['UP031', 'D']
